fiftys=input("Enter number of 50 euro banknotes:")
twentys=input("Enter number of 20 euro banknotes:")
tens=input("Enter number of 10 euro banknotes:")
fives=input("Enter number of 5 euro banknotes:")
twos=input("Enter number of 2 euro coins:")
ones=input("Enter number of 1 euro coins:")
total=int(fiftys)*50+ int(twentys)*20+int(tens)*10+int(fives)*5+int(twos)*2+int(ones)
print("You have", total,"euros")
